# Generated by Django 5.2.6 on 2025-09-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_player_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="adaptability",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="communication",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="decision_making",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="flexibility",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="game_awareness",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="player_awareness",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="positioning",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="resource_awareness",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="speed",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="stamina",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="player",
            name="teamwork",
            field=models.IntegerField(default=50),
        ),
    ]
