# Generated by Django 5.2.6 on 2025-10-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0005_alter_player_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="role",
            field=models.CharField(
                choices=[
                    ("commander", "Commander"),
                    ("heavy", "Heavy Weapons"),
                    ("scout", "Scout"),
                    ("medic", "Medic"),
                    ("ammo", "Ammo"),
                ],
                max_length=20,
            ),
        ),
    ]
