# Generated by Django 5.2.6 on 2026-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_player_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('commander', 'Commander'), ('heavy', 'Heavy Weapons'), ('scout', 'Scout'), ('medic', 'Medic'), ('ammo', 'Ammo'), ('bench', 'Bench')], max_length=20),
        ),
    ]
