# Generated by Django 5.2.6 on 2026-05-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0009_alter_player_offensive_synergy_alter_player_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="height",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="player",
            name="home_site",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="started_playing_age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="total_games",
            field=models.IntegerField(default=0),
        ),
    ]
