# Generated by Django 5.2.6 on 2026-06-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0010_player_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_draw_team",
            field=models.BooleanField(default=False),
        ),
    ]
