# Generated by Django 5.2.6 on 2026-06-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_team_is_draw_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="potential",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
