# Generated by Django 5.2.6 on 2026-06-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0012_player_potential"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="salary",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="budget_coaching",
            field=models.PositiveSmallIntegerField(default=34),
        ),
        migrations.AddField(
            model_name="team",
            name="budget_facilities",
            field=models.PositiveSmallIntegerField(default=34),
        ),
        migrations.AddField(
            model_name="team",
            name="budget_scouting",
            field=models.PositiveSmallIntegerField(default=34),
        ),
        migrations.AddField(
            model_name="team",
            name="cash",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="team",
            name="ticket_price",
            field=models.FloatField(default=0.0),
        ),
    ]
