# Generated by Django 5.2.6 on 2026-05-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapBaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_type', models.CharField(max_length=20)),
                ('x_px', models.IntegerField()),
                ('y_px', models.IntegerField()),
                ('arena_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_configs', to='core.arenamap')),
            ],
            options={
                'unique_together': {('arena_map', 'base_type')},
            },
        ),
    ]
