# Generated by Django 5.2.6 on 2026-05-12 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_basesightlineconfig_sightlineconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeavyStrongSpotsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_size", models.IntegerField()),
                ("cells", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arena_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strong_spots_configs",
                        to="core.arenamap",
                    ),
                ),
            ],
            options={
                "unique_together": {("arena_map", "zone_size")},
            },
        ),
        migrations.CreateModel(
            name="MapCellRankingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_size", models.IntegerField()),
                ("ranked_cells", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "arena_map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_rankings",
                        to="core.arenamap",
                    ),
                ),
            ],
            options={
                "unique_together": {("arena_map", "zone_size")},
            },
        ),
    ]
