LASERFORCE_SITES: list[str] = [
    "San Marcos",
    "Sacramento",
    "City of Industry",
    "Cedar City",
    "Saint George",
    "Loveland",
    "Detroit",
    "New York",
    "Auckland",
    "Brisbane",
    "England",
    "Czech Republic",
]

PLAYER_NAMES: list[str] = [
    "Hammer",
    "Beanz",
    "Evol",
    "Britton",
    "DoNotPassGo",
    "10,10,9",
    "Sanchez",
    "DiscoStu",
    "Fenrir",
    "Fox",
    "Alex",
    "Zerg",
    "Jackal",
    "Axeman",
    "MamaBear",
    "Nobody",
    "RazorWires",
    "DogeBlaster",
    "WOZ",
    "Death Knight",
    "Kodama",
    "Odin",
    "DiscoMonkee",
    "Autumn",
    "Applesauce",
    "Dill",
    "Sweets",
    "EboMike",
    "Anchovy",
    "Survivor",
    "Ender",
    "Halange",
    "RainbowPanther",
    "Slaughtermelon",
    "Snuffelz",
    "Cope",
    "Medz",
    "MetalFace",
    "Chaser",
    "Rockwood",
    "Sgt. Tucker",
    "The Rook",
    "Sparkz",
    "Judoku",
    "The Babe",
    "Asra",
    "GHOST",
    "Fear Turkey",
    "Liz",
    "Corbin",
    "Carsen",
    "Celly",
    "Blackout",
    "Luke",
    "RedNeckTech",
    "Sn3aky",
    "Grumpy",
    "PapaSmurf",
    "Skillz",
    "Gladr",
    "Twin",
    "PrawnBoy",
    "Leech",
    "Vulcan",
    "Firesword",
    "Lil Bit",
    "Stealth Elf",
    "Lil Cody Collins",
    "Razz",
    "Commander",
    "XCountry",
    "Shadow ☺",
    "Loading...",
    "Super Dave",
    "Paulie",
    "Just Jay ☺",
    "Nolandooo",
    "Spooky",
    "High Tower",
    "Insulified",
    "Luffy",
    "John Warhammer",
    "Shadow Dagger",
    "Wowza",
    "Anubis ☥",
    "Junkrat ♥",
    "Stealth",
    "SupremeKev",
    "Twix ☺",
    "Bagel",
    "Das",
    "CorgisRUs☺",
    "R3D Faction",
    "Son of Athena",
    "Neko",
    "BreeDai",
    "Roadrunner",
    "#!TRIPWIRE!#",
    "-=Valroc=-",
    "2KKing",
    "7",
    "< M 1 C r O >",
    "@s1mply0k",
    "A D H D",
    "A wiSaRd Ahhhhh",
    "A.n.g.e.l",
    "Ace",
    "Acer",
    "Adds",
    "Anarki",
    "Angry Joe",
    "AppleSauce!",
    "Archdruid",
    "Aristocrat",
    "AshVD",
    "Assassin",
    "Auest",
    "Axman",
    "Aztec",
    "Bam Bam",
    "Basil",
    "Bayani",
    "Beard-diful",
    "Bearded Joe",
    "Ben",
    "Bigdog",
    "Black Hammer",
    "Blackbeard",
    "BladeZ",
    "Bounce",
    "Brew",
    "Bromatized",
    "Bronwyn",
    "C.Arsyn",
    "Calvin Kline",
    "Celly Bee",
    "Cobra",
    "Cody'sTinyShirt",
    "Compgeek",
    "Cookie",
    "CoolBeans",
    "Cordash",
    "Crackshot Fox",
    "Crystal Camp",
    "Custardio",
    "Cyclone",
    "DRock",
    "Dairylea",
    "Damage",
    "Dank Memer",
    "Danta",
    "Dark Knight",
    "Dart",
    "DayMon",
    "Death2All",
    "DezzaConda",
    "Dmihawk",
    "Dom",
    "Doom-Six",
    "Dozer",
    "Dr Feel Good",
    "Dr. Wookie",
    "Dubya",
    "Duckman",
    "Dude",
    "DudeBoganEsq",
    "DyscoMonkee",
    "El Diablo",
    "ElderBerry",
    "Entity",
    "Esnc",
    "Evol hate on me",
    "Feeder",
    "Fire-Sword",
    "Fishie",
    "Fonzoreli",
    "Freddo",
    "Fried Joe Fish",
    "G H O 5 T",
    "Gammer =)",
    "Gareth",
    "Gascon",
    "Gaza",
    "Glaedr",
    "Golden Pony Boy",
    "Goldfish",
    "Grandmaster",
    "Greymatter",
    "Grizzly",
    "GuyNextDoor",
    "Hockeygy99",
    "Hooded Joe",
    "Hoodlum",
    "Hurricane",
    "Im Last Place",
    "Imathis",
    "Inferno",
    "ItsFreIfUBoofIt",
    "Ivy",
    "Izzy",
    "J.F.K",
    "Jaeosaurus",
    "Jak Jak",
    "Jake",
    "Jeff Pecks",
    "JerBear",
    "Jerome",
    "Jigs",
    "Joe Next Door",
    "JohnTheBaptist",
    "Kai",
    "Kamikaze",
    "Kha'ato",
    "Khadrim",
    "Kiingtong",
    "King Fox",
    "Knightmare",
    "Knowitall",
    "Krypt",
    "LaJou",
    "LazerDude",
    "Lei Lei",
    "LeroyRWJenkins",
    "LiL Blaster",
    "LilKat",
    "LilSnowflake",
    "Lilbo",
    "Loki",
    "LoneSoul",
    "Lucidun",
    "Lurch",
    "Lusky",
    "Lyte",
    "MadDawg",
    "Mallet",
    "Maniac",
    "Mario",
    "Mark",
    "Maroon",
    "Maximus",
    "Merc 1",
    "Merc 2",
    "Metalface",
    "Minette",
    "Minion",
    "Mo Fox Given",
    "Monkey Crap",
    "Mookie",
    "Morange!!!",
    "MorningStar",
    "Morphen",
    "Mr Doom",
    "MrMiSCHiEF",
    "MyLittlePony",
    "N00b",
    "Nami Swan",
    "NightFury",
    "Nimitz",
    "Ninja",
    "Ninja Jack",
    "Nite Owl",
    "No Cole No",
    "Nomad",
    "OG mudcrab",
    "Oddum",
    "Odin's Fist",
    "Off the Wall",
    "Oguri Cap",
    "OldManThanatos",
    "Otaku Lord",
    "P H N T M",
    "POS Blick",
    "PandaFuFu",
    "Panther",
    "Papa Joe",
    "Pebbles",
    "Phant0m",
    "Phynn",
    "Pintsize",
    "Poison Ivy",
    "Poopies",
    "Potter",
    "Prawn Boy",
    "Prd > Oldskool",
    "Princess",
    "Princess Peach",
    "Qeronic",
    "Queen",
    "R3DFaction",
    "Rags",
    "RaidenGL",
    "RainbowBunchie",
    "Rainbowbunchie2",
    "Reacher",
    "Recrustable",
    "Reya Blackthorn",
    "Rice Krispy",
    "Rich",
    "Rook",
    "Rooks2NR",
    "Rosey",
    "Rr Uu Ss Tt Yy",
    "Ryujin",
    "S C Y T H E",
    "SHaGZ",
    "SHaGaDeLiC",
    "Sadders",
    "Samurai",
    "Scamp",
    "SchwiftyTaco",
    "ScoonybooJonson",
    "Scorpion",
    "Scrapz",
    "Screaver",
    "Selenago",
    "Sexy Dezza",
    "Sexy LaserDude",
    "Sexy Nilthing",
    "Sexy Striker",
    "Sexy mEoW!",
    "SgtTucker",
    "Shadow_Wolf",
    "Sharp Shooter",
    "Siony",
    "Sir Polidor",
    "Smally McSmall",
    "Smuppet",
    "Snd",
    "Sneak",
    "Sneaky",
    "Snowflake",
    "Snufflez",
    "Soy Boy",
    "Sp00ky",
    "Squiza",
    "Sslaughtermelon",
    "Stallion",
    "Starkiller",
    "Straight2VHS",
    "Striker",
    "SuperMarioBros",
    "Taipan",
    "Tandaor",
    "Tank",
    "The Fear Turkey",
    "The Gizzard ;)",
    "The Gracken",
    "The Preacher",
    "The Rat",
    "TheBabe",
    "TheGod",
    "TheUnnamedSnipe",
    "The_Preacher",
    "Thee Merlin",
    "Thomiiik",
    "Thor",
    "Thunder",
    "Tilt",
    "Tinpot",
    "Tragedy",
    "TravisMcdonald",
    "Trips",
    "Try HARDER",
    "Tsantua",
    "Virus",
    "Wazza",
    "Wildcard",
    "Wilson",
    "Wolfman",
    "Xallai",
    "XxThe!13th!xX",
    "Yama",
    "Yipsty",
    "Yo Get On Apex",
    "Z Merlin",
    "ataPATasaurus",
    "boomTRAIN",
    "kEYHOLE",
    "onceORtwice",
    "xStockeRx",
    "xVenoMx",
    "xoxLiLBiTxox",
    "~Troyoda~",
    "฿ Ⱡ ₳ ₵ ₭ Ø Ʉ ₮",
    "ᵐ⁰ᵐʸˢᵍᵒᵇˡᶦⁿ",
    "♥Sabo♥ didi hi",
]
