# Generated by Django 5.2.6 on 2025-09-30 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
        ('teams', '0003_player_adaptability_player_communication_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerroundstate',
            old_name='lives',
            new_name='starting_lives',
        ),
        migrations.RenameField(
            model_name='playerroundstate',
            old_name='missiles',
            new_name='starting_missiles',
        ),
        migrations.RenameField(
            model_name='playerroundstate',
            old_name='shots',
            new_name='starting_shots',
        ),
        migrations.RenameField(
            model_name='playerroundstate',
            old_name='special_points',
            new_name='starting_special',
        ),
        migrations.RenameField(
            model_name='singleround',
            old_name='blue_eliminated',
            new_name='blue_team_eliminated',
        ),
        migrations.RenameField(
            model_name='singleround',
            old_name='red_eliminated',
            new_name='red_team_eliminated',
        ),
        migrations.AddField(
            model_name='gameround',
            name='blue_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='date_played',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameround',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameround',
            name='red_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameround',
            name='team_blue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blue_game_rounds', to='teams.team'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='team_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_game_rounds', to='teams.team'),
        ),
        migrations.AddField(
            model_name='gameround',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_game_rounds', to='teams.team'),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='final_missiles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='final_special',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='missiles_fired',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='specials_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='tags_made',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='times_tagged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='was_eliminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_rounds', to='matches.match'),
        ),
        migrations.AlterField(
            model_name='playerroundstate',
            name='game_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_states', to='matches.gameround'),
        ),
        migrations.DeleteModel(
            name='TagEvent',
        ),
    ]
