# Generated by Django 5.2.6 on 2025-10-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_playerroundstate_special_active_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerroundstate',
            name='resupplies_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerroundstate',
            name='special_active_until',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
