# Generated by Django 5.2.6 on 2025-10-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_rename_missiles_fired_playerroundstate_missiles_landed'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerroundstate',
            name='is_hiding',
            field=models.BooleanField(default=False),
        ),
    ]
