# Generated by Django 5.2.6 on 2025-10-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_playerroundstate_was_eliminated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerroundstate',
            name='ally_nuke_cancels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='enemy_nuke_cancels',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerroundstate',
            name='own_specials_cancelled',
            field=models.IntegerField(default=0),
        ),
    ]
