# Generated by Django 5.2.6 on 2026-05-01 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0015_playerroundstate_lives_lost_to_nukes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playerroundstate",
            name="shot_power",
        ),
    ]
