# Generated by Django 5.2.6 on 2026-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0020_map01_cell_grid"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerroundstate",
            name="combo_resupply_count",
            field=models.IntegerField(default=0),
        ),
    ]
