# Generated by Django 5.2.6 on 2026-05-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0021_playerroundstate_combo_resupply_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerroundstate",
            name="missile_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerroundstate",
            name="seconds_active",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerroundstate",
            name="seconds_not_targetable",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerroundstate",
            name="seconds_reset_window",
            field=models.IntegerField(default=0),
        ),
    ]
