# Generated by Django 5.2.6 on 2026-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0022_playerroundstate_missile_points_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playerroundstate",
            old_name="seconds_active",
            new_name="ticks_active",
        ),
        migrations.RenameField(
            model_name="playerroundstate",
            old_name="seconds_not_targetable",
            new_name="ticks_not_targetable",
        ),
        migrations.RenameField(
            model_name="playerroundstate",
            old_name="seconds_reset_window",
            new_name="ticks_reset_window",
        ),
        migrations.AlterField(
            model_name="gameevent",
            name="timestamp",
            field=models.IntegerField(
                help_text="Ticks into the round (0-1800 for a 15 min game; 1 tick = 0.5 s)"
            ),
        ),
        migrations.AlterField(
            model_name="gameround",
            name="eliminated_at",
            field=models.IntegerField(default=1801),
        ),
        migrations.AlterField(
            model_name="match",
            name="round1_eliminated_at",
            field=models.IntegerField(default=1801),
        ),
        migrations.AlterField(
            model_name="match",
            name="round2_eliminated_at",
            field=models.IntegerField(default=1801),
        ),
        migrations.AlterField(
            model_name="playerroundstate",
            name="was_eliminated_at",
            field=models.IntegerField(default=1801),
        ),
    ]
