# Generated by Django 5.2.6 on 2026-05-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "matches",
            "0023_rename_seconds_active_playerroundstate_ticks_active_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gameround",
            name="rng_seed",
            field=models.BigIntegerField(
                blank=True,
                help_text="63-bit integer seed passed to random.seed() before simulating this round; null = round predates SIM-07 / not replayable. Replay is exact only if rosters and map config are unchanged.",
                null=True,
            ),
        ),
    ]
