# Generated by Django 5.2.6 on 2026-05-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0024_gameround_rng_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tag", "Tag"),
                    ("locking", "Missile Lock Start"),
                    ("missiled", "Missile Resolved"),
                    ("special", "Special Activated"),
                    ("miss", "Missed Shot"),
                    ("resupply_ammo", "Ammo Resupply"),
                    ("resupply_lives", "Medic Heal"),
                    ("elimination", "Player Eliminated"),
                    ("team_elimination", "Team Eliminated"),
                ],
                max_length=20,
            ),
        ),
    ]
