# Generated by Django 5.2.6 on 2026-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0026_gameround_cell_occupancy_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameround",
            name="highlights_json",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="gameevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tag", "Tag"),
                    ("locking", "Missile Lock Start"),
                    ("missiled", "Missile Resolved"),
                    ("special", "Special Activated"),
                    ("miss", "Missed Shot"),
                    ("resupply_ammo", "Ammo Resupply"),
                    ("resupply_lives", "Medic Heal"),
                    ("elimination", "Player Eliminated"),
                    ("team_elimination", "Team Eliminated"),
                    ("nuke_cancelled", "Nuke Cancelled"),
                    ("medic_reset", "Medic Reset"),
                ],
                max_length=20,
            ),
        ),
    ]
