# Generated by Django 5.2.6 on 2026-05-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0027_gameround_highlights_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameround",
            name="is_simulated",
            field=models.BooleanField(default=True),
        ),
    ]
