# Generated by Django 5.2.6 on 2026-05-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0031_season_map_mode_pool"),
        ("teams", "0010_player_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="free_agent_pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="free_agent_pool_for",
                to="teams.team",
            ),
        ),
    ]
