# Generated by Django 5.2.6 (LG-02a tournament). Renamed from the
# autogenerated 0033_tournament_bracketnode_tournamentparticipant.py — the
# seam contract pinned 0032_tournament.py but 0032 is already taken by
# 0032_league_free_agent_pool, so the next free number 0033 is used.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0032_league_free_agent_pool"),
        ("teams", "0010_player_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "format",
                    models.CharField(
                        choices=[("single_elimination", "Single elimination")],
                        default="single_elimination",
                        max_length=32,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("setup", "Setup"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                        ],
                        default="setup",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "champion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tournaments_won",
                        to="teams.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.PositiveIntegerField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="matches.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["seed"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "seed"), name="uniq_tournament_seed"
                    ),
                    models.UniqueConstraint(
                        fields=("tournament", "team"), name="uniq_tournament_team"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BracketNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bracket_round", models.PositiveIntegerField()),
                ("position", models.PositiveIntegerField()),
                ("seed_a", models.PositiveIntegerField(blank=True, null=True)),
                ("seed_b", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "advances_to_slot",
                    models.CharField(
                        blank=True,
                        choices=[("a", "team_a"), ("b", "team_b")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("is_bye", models.BooleanField(default=False)),
                (
                    "advances_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feeders",
                        to="matches.bracketnode",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bracket_node",
                        to="matches.match",
                    ),
                ),
                (
                    "team_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="teams.team",
                    ),
                ),
                (
                    "team_b",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="teams.team",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="teams.team",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="matches.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["bracket_round", "position"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "bracket_round", "position"),
                        name="uniq_tournament_round_position",
                    )
                ],
            },
        ),
    ]
