# Generated by Django 5.2.6 on 2026-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0034_tournament_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="series_length",
        ),
        migrations.AddField(
            model_name="bracketnode",
            name="series_length",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="tournament",
            name="earlier_series_length",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Best of 1"), (3, "Best of 3"), (5, "Best of 5")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="final_series_length",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Best of 1"), (3, "Best of 3"), (5, "Best of 5")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="quarterfinal_series_length",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Best of 1"), (3, "Best of 3"), (5, "Best of 5")],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="semifinal_series_length",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Best of 1"), (3, "Best of 3"), (5, "Best of 5")],
                default=1,
            ),
        ),
    ]
