# Generated by Django 5.2.6 on 2026-06-04 (LG-02x-1 Random Draw).

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0039_tournament_swiss"),
        ("teams", "0011_team_is_draw_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="team_assembly",
            field=models.CharField(
                choices=[
                    ("preset", "Preset teams"),
                    ("random_draw", "Random draw player pool"),
                ],
                default="preset",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="role_assignment_mode",
            field=models.CharField(
                choices=[
                    ("random", "Random per team per Round"),
                    ("per_tier", "Per-tier bijection (both teams)"),
                ],
                default="random",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="TournamentPlayerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tier", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "drawn_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="drawn_player_entries",
                        to="teams.team",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_entries",
                        to="teams.player",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_entries",
                        to="matches.tournament",
                    ),
                ),
            ],
            options={
                "ordering": ["tournament_id", "tier", "player_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tournament", "player"),
                        name="uniq_tournament_player_entry",
                    )
                ],
            },
        ),
    ]
