# Generated by Django 5.2.6 on 2026-06-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0041_season_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonphase",
            name="schedule_format",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="seasonphase",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="season_phases",
                to="matches.tournament",
            ),
        ),
    ]
