# Generated by Django 5.2.6 on 2026-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0045_seasonphase_tournament_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="seasonphase",
            name="tournament_format",
            field=models.CharField(
                choices=[
                    ("single_elimination", "Single elimination"),
                    ("double_elimination", "Double elimination"),
                    ("round_robin", "Round robin"),
                    ("round_robin_double_elim", "Round robin → Double elimination"),
                    ("swiss", "Swiss"),
                ],
                default="single_elimination",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="seasonphase",
            name="tournament_cut",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
