# Generated by Django 5.2.6 on 2026-06-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0047_seasonphase_tournament_subconfig"),
        ("teams", "0011_team_is_draw_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSeasonRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("player_awareness", models.IntegerField()),
                ("game_awareness", models.IntegerField()),
                ("resource_awareness", models.IntegerField()),
                ("decision_making", models.IntegerField()),
                ("positioning", models.IntegerField()),
                ("stamina", models.IntegerField()),
                ("speed", models.IntegerField()),
                ("flexibility", models.IntegerField()),
                ("adaptability", models.IntegerField()),
                ("communication", models.IntegerField()),
                ("teamwork", models.IntegerField()),
                ("Offensive_synergy", models.IntegerField()),
                ("defensive_synergy", models.IntegerField()),
                ("midfield_synergy", models.IntegerField()),
                ("resupply_synergy", models.IntegerField()),
                ("resupply_efficiency", models.IntegerField()),
                ("accuracy", models.IntegerField()),
                ("survival", models.IntegerField()),
                ("special_usage", models.IntegerField()),
                ("overall_rating", models.FloatField()),
                ("potential", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_ratings",
                        to="teams.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_ratings",
                        to="matches.season",
                    ),
                ),
            ],
            options={
                "ordering": ["player_id", "season_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "season"), name="uniq_player_season_rating"
                    )
                ],
            },
        ),
    ]
