# Generated by Django 5.2.6 on 2026-06-16 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0048_playerseasonrating"),
        ("teams", "0012_player_potential"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wins_delta", models.FloatField()),
                ("playoffs_delta", models.FloatField()),
                ("money_delta", models.FloatField(default=0.0)),
                ("wins_total", models.FloatField()),
                ("playoffs_total", models.FloatField()),
                ("money_total", models.FloatField(default=0.0)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("retained", "Retained"),
                            ("hot_seat", "Hot seat"),
                            ("fired", "Fired"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hot_seat_level", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_evaluations",
                        to="matches.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_evaluations",
                        to="matches.season",
                    ),
                ),
                (
                    "team_managed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["league_id", "season_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("league", "season"),
                        name="uniq_league_season_owner_evaluation",
                    )
                ],
            },
        ),
    ]
