# Generated by Django 5.2.6 on 2026-06-16 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0049_ownerevaluation"),
        ("teams", "0013_player_salary_team_finance"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="finance_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="TeamSeasonFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket", models.FloatField(default=0.0)),
                ("national_tv", models.FloatField(default=0.0)),
                ("local_tv", models.FloatField(default=0.0)),
                ("sponsor", models.FloatField(default=0.0)),
                ("merch", models.FloatField(default=0.0)),
                ("payroll", models.FloatField(default=0.0)),
                ("scouting_cost", models.FloatField(default=0.0)),
                ("coaching_cost", models.FloatField(default=0.0)),
                ("facilities_cost", models.FloatField(default=0.0)),
                ("luxury_tax", models.FloatField(default=0.0)),
                ("min_payroll_penalty", models.FloatField(default=0.0)),
                ("revenue", models.FloatField(default=0.0)),
                ("expenses", models.FloatField(default=0.0)),
                ("profit", models.FloatField(default=0.0)),
                ("hype", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_finances",
                        to="matches.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="season_finances",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["season_id", "team_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "season"), name="uniq_team_season_finance"
                    )
                ],
            },
        ),
    ]
