# Generated by Django 5.2.6 on 2026-06-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0052_teamseasonfinance_health_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="challenge_fired_luxury_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ownerevaluation",
            name="fired_reason",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("owner_mood", "Owner mood"),
                    ("luxury_tax", "Luxury tax"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
