# Generated by Django 5.2.6 on 2026-06-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0053_fin05_luxury_tax_firing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="season",
            name="map_mode",
            field=models.CharField(
                choices=[
                    ("none", "3-zone fallback"),
                    ("single", "Single map"),
                    ("random_per_round", "Random per Round"),
                    ("rotate_by_matchday", "Rotate by matchday"),
                ],
                default="none",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="map_rotation_ids_json",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="starting_map_rotation_ids_json",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
