# Generated by Django 5.2.6 on 2026-06-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0055_gameround_fidelity_roster_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="active_play_job_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="season",
            name="play_cancel_requested",
            field=models.BooleanField(default=False),
        ),
    ]
