# Generated by Django 5.2.6 on 2026-06-29 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0056_season_play_job_cancel"),
        ("teams", "0014_player_team_health_injury"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ordinal", models.PositiveSmallIntegerField()),
                (
                    "starting_team_ids_json",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conferences",
                        to="matches.season",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(related_name="conferences", to="teams.team"),
                ),
            ],
            options={
                "ordering": ["ordinal"],
            },
        ),
        migrations.AddField(
            model_name="match",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches",
                to="matches.conference",
            ),
        ),
        migrations.AddConstraint(
            model_name="conference",
            constraint=models.UniqueConstraint(
                fields=("season", "ordinal"), name="uniq_season_conference_ordinal"
            ),
        ),
    ]
