# Generated by Django 5.2.6 on 2026-09-03 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0057_conference_match_conference"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="conference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="matches.conference",
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="season_phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="regional_tournaments",
                to="matches.seasonphase",
            ),
        ),
    ]
