# Generated by Django 5.2.6 on 2026-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0058_tournament_regional_linkage"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="qualifier_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not a qualifier bracket"),
                    ("regional_playoff", "Regional playoff"),
                    ("last_chance", "Last-chance qualifier"),
                ],
                default="",
                max_length=16,
            ),
        ),
    ]
