# Generated by Django 5.2.6 on 2026-09-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matches", "0059_tournament_qualifier_stage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seasonphase",
            name="tournament_mode",
            field=models.CharField(
                choices=[
                    ("standings", "Season-ending: from Standings"),
                    ("strength", "Mid-season: by team strength"),
                    ("unseeded", "Mid-season: random seed"),
                    ("random_draw", "Mid-season: drawn pool -> RR->DE"),
                    ("worlds", "Worlds"),
                ],
                default="standings",
                max_length=16,
            ),
        ),
    ]
